### ISSUE TITLE
Notes seen as Lessons

### ISSUE THREAD

**Issue by dobhela** [Exerra/eklase-wrapper#1]
If the teacher adds a note to the day, it is recognized as a lesson
![image](https://user-images.githubusercontent.com/82323135/164240919-48ab8ffb-f6fb-4501-aa97-4d091dcfe144.png)
![Screenshot_5](https://user-images.githubusercontent.com/82323135/164241588-cc555bd3-6934-4ecb-a74b-c3f81163002f.png)

**Comment by Exerra** [comment]
I prolly can check if the dot is there and use that
